version: "3"
services:
  api:
    image: thepixelboy/fastapi
    depends_on:
      - postgres
    ports:
      - 80:8000
    # env_file:
    #   - ./.env
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
